services:
  techhala-frontend-dev:
    extends:
      file: docker-compose.common.yml
      service: techhala-frontend-common
    environment:
      - API_URL=http://techhala-backend-dev:8080
      - SENTRY_DISABLED=true
    build:
      dockerfile: docker/Dockerfile.dev.ui
    volumes:
      - ./techhala-ui:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - techhala-backend-dev

  techhala-backend-dev:
    extends:
      file: docker-compose.common.yml
      service: techhala-backend-common
    build:
      dockerfile: docker/Dockerfile.dev.api
    volumes:
      - .:/app
      - ./state:/state

  techhala-websocket-server:
    extends:
      file: docker-compose.common.yml
      service: techhala-websocket-server-common
