services:
  - type: worker
    name: techhala-worker
    env: python
    buildCommand: pip install .
    startCommand: techhala -v run --interval 300 --alert-url https://raw.githubusercontent.com/keephq/keep/main/examples/alerts/db_disk_space.yml
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.1
      - key: KEEP_PROVIDER_SLACK_DEMO
        sync: false
