route:
  receiver: "keep"
  group_by: ["alertname"]
  group_wait: 15s
  group_interval: 15s
  repeat_interval: 1m
receivers:
  - name: "keep"
    webhook_configs:
      - url: "http://keep-backend-dev:8080/alerts/event/prometheus"
        send_resolved: true
        http_config:
          basic_auth:
            username: api_key
            password: cfe879c6-9423-4c1a-abd8-01e648bf4976
