receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:
  attributes:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: container
      - action: insert
        key: loki.format
        value: raw
  batch:

  memory_limiter:
    check_interval: 1s
    limit_percentage: 65
    spike_limit_percentage: 20

# Alternatively, add additional exporters for the backend of your choice and update the
# pipelines below
exporters:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

  otlp/elastic:
    endpoint: apm:8200
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:9100"
    namespace: keep
    const_labels:
      label1: value1
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheus]

    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, attributes]
      exporters: [loki]
