[sources.docker_logs]
type = "docker_logs"
auto_partial_merge = true
include_labels = ["vector_scrape=true"]
partial_event_marker_field = "_partial"
retry_backoff_secs = 2


[sinks.loki]
type = "loki"
inputs = ["docker_logs"]
endpoint = "http://loki:3100"
encoding.codec = "json"

[sinks.loki.labels]
source = "vector"
service = "{{ label.service }}"
spanID = "{{ message.otelSpanID }}"
